config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :email_addresses, except: [:index, :show]
  resources :phone_numbers, except: [:index, :show]
  resources :people

end

app/models/company.rb
class Company < ActiveRecord::Base
  include Contact
  validates :name, presence: true

  def to_s
    "#{name}"
  end
end

app/models/contact.rb
module Contact
  extend ActiveSupport::Concern

  included do
    has_many :phone_numbers, as: :contact
    has_many :email_addresses, as: :contact
  end

  module ClassMethods
  end
end

app/models/email_address.rb
class EmailAddress < ActiveRecord::Base
  validates :address, :contact_id, presence: true
  belongs_to :contact, polymorphic: true
end

app/models/person.rb
class Person < ActiveRecord::Base
  include Contact
  validates :first_name, :last_name, presence: true

  def to_s
    "#{first_name} #{last_name}"
  end
end

app/models/phone_number.rb
class PhoneNumber < ActiveRecord::Base
  validates :number, :contact_id, presence: true
  belongs_to :contact, polymorphic: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def find_resource
    class_name = params[:controller].singularize
    klass = class_name.camelize.constantize
    self.instance_variable_set '@' + class_name, klass.find(params[:id])
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :find_resource, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name)
    end
end

app/controllers/email_addresses_controller.rb
class EmailAddressesController < ApplicationController
  before_action :find_resource, only: [:edit, :update, :destroy]

  # GET /email_addresses/new
  def new
    @email_address = EmailAddress.new(contact_id: params[:contact_id], contact_type: params[:contact_type])
  end

  # GET /email_addresses/1/edit
  def edit
  end

  # POST /email_addresses
  # POST /email_addresses.json
  def create
    @email_address = EmailAddress.new(email_address_params)

    respond_to do |format|
      if @email_address.save
        format.html { redirect_to @email_address.contact, notice: 'Email address was successfully created.' }
        format.json { render :show, status: :created, location: @email_address }
      else
        format.html { render :new }
        format.json { render json: @email_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /email_addresses/1
  # PATCH/PUT /email_addresses/1.json
  def update
    respond_to do |format|
      if @email_address.update(email_address_params)
        format.html { redirect_to @email_address.contact, notice: 'Email address was successfully updated.' }
        format.json { render :show, status: :ok, location: @email_address }
      else
        format.html { render :edit }
        format.json { render json: @email_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /email_addresses/1
  # DELETE /email_addresses/1.json
  def destroy
    @email_address.destroy
    respond_to do |format|
      format.html { redirect_to @email_address.contact, notice: 'Email address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def email_address_params
      params.require(:email_address).permit(:address, :contact_id, :contact_type)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :find_resource, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:first_name, :last_name)
    end
end

app/controllers/phone_numbers_controller.rb
class PhoneNumbersController < ApplicationController
  before_action :find_resource, only: [:edit, :update, :destroy]

  # GET /phone_numbers/new
  def new
    @phone_number = PhoneNumber.new(contact_id: params[:contact_id], contact_type: params[:contact_type])
  end

  # GET /phone_numbers/1/edit
  def edit
  end

  # POST /phone_numbers
  # POST /phone_numbers.json
  def create
    @phone_number = PhoneNumber.new(phone_number_params)

    respond_to do |format|
      if @phone_number.save
        format.html { redirect_to @phone_number.contact, notice: 'Phone number was successfully created.' }
        format.json { render :show, status: :created, location: @phone_number }
      else
        format.html { render :new }
        format.json { render json: @phone_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phone_numbers/1
  # PATCH/PUT /phone_numbers/1.json
  def update
    respond_to do |format|
      if @phone_number.update(phone_number_params)
        format.html { redirect_to @phone_number.contact, notice: 'Phone number was successfully updated.' }
        format.json { render :show, status: :ok, location: @phone_number }
      else
        format.html { render :edit }
        format.json { render json: @phone_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phone_numbers/1
  # DELETE /phone_numbers/1.json
  def destroy
    @phone_number.destroy
    respond_to do |format|
      format.html { redirect_to @phone_number.contact, notice: 'Phone number was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def phone_number_params
      params.require(:phone_number).permit(:number, :contact_id, :contact_type)
    end
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing <%= @company %></h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Actions</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company %></td>
        <td>
          <ul class='actions'>
            <li><%= link_to 'Show', company %></li>
            <li><%= link_to 'Edit', edit_company_path(company) %></li>
            <li><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></li>
          </ul>
        </td>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path, id: 'new_company' %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<div class='company'>
  <p id="notice"><%= notice %></p>

  <h1><%= @company %></h1

  <%= render 'phone_numbers/phone_numbers', phone_numbers: @company.phone_numbers %>

  <p><%= link_to 'Add phone number', new_phone_number_path(contact_id: @company.id, contact_type: 'Company') %></p>

  <%= render 'email_addresses/email_addresses', email_addresses: @company.email_addresses %>

  <p><%= link_to 'Add email address', new_email_address_path(contact_id: @company.id, contact_type: 'Company') %></p>

  <%= link_to 'Edit', edit_company_path(@company) %> |
  <%= link_to 'Back', companies_path %>
</div>

app/views/email_addresses/_email_addresses.html.erb
<p>
  <strong>Email addresses:</strong>
  <ul>
    <% email_addresses.each do |email| %>
      <li>
        <%= email.address %>&nbsp;
        <%= link_to 'edit', edit_email_address_path(email) %>&nbsp;
        <%= link_to 'delete', email_address_path(email), method: 'delete' %>
        </li>
    <% end %>
  </ul>
</p>

app/views/email_addresses/_form.html.erb
<%= form_for(@email_address) do |f| %>
  <% if @email_address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@email_address.errors.count, "error") %> prohibited this email_address from being saved:</h2>

      <ul>
      <% @email_address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.hidden_field :contact_id %>
  </div>
  <div class="field">
    <%= f.hidden_field :contact_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/email_addresses/edit.html.erb
<h1><%= "Editing #{@email_address.address} for #{@email_address.contact}" %></h1>

<%= render 'form' %>

<%= link_to 'Back', @email_address.contact %>

app/views/email_addresses/new.html.erb
<h1><%= "New Email Address for #{@email_address.contact}" %></h1>

<%= render 'form' %>

<%= link_to 'Back', @email_address.contact %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ContactManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing <%= @person %></h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing People</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Actions</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person %></td>
        <td>
          <ul class='actions'>
            <li><%= link_to 'Show', person %></li>
            <li><%= link_to 'Edit', edit_person_path(person) %></li>
            <li><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></li>
          </ul>
        </td>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path, id: 'new_person' %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<div class='people'>
  <p id="notice"><%= notice %></p>

  <h1><%= @person %></h1>

  <%= render 'phone_numbers/phone_numbers', phone_numbers: @person.phone_numbers %>

  <p><%= link_to 'Add phone number', new_phone_number_path(contact_id: @person.id, contact_type: 'Person') %></p>

  <%= render 'email_addresses/email_addresses', email_addresses: @person.email_addresses %>

  <p><%= link_to 'Add email address', new_email_address_path(contact_id: @person.id, contact_type: 'Person') %></p>

  <%= link_to 'Edit', edit_person_path(@person) %> |
  <%= link_to 'Back', people_path %>
</div>

app/views/phone_numbers/_form.html.erb
<%= form_for(@phone_number) do |f| %>
  <% if @phone_number.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@phone_number.errors.count, "error") %> prohibited this phone_number from being saved:</h2>

      <ul>
      <% @phone_number.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.hidden_field :contact_id %>
  </div>
  <div class="field">
    <%= f.hidden_field :contact_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/phone_numbers/_phone_numbers.html.erb
<p>
  <strong>Phone numbers:</strong>
  <ul>
    <% phone_numbers.each do |phone| %>
      <li>
        <%= phone.number %>&nbsp;
        <%= link_to 'edit', edit_phone_number_path(phone) %>&nbsp;
        <%= link_to 'delete', phone_number_path(phone), method: 'delete' %>
        </li>
    <% end %>
  </ul>
</p>

app/views/phone_numbers/edit.html.erb
<h1><%= "Editing #{@phone_number.number} for #{@phone_number.contact}" %></h1>

<%= render 'form' %>

<%= link_to 'Back', @phone_number.contact %>

app/views/phone_numbers/new.html.erb
<h1><%= "New Phone Number for #{@phone_number.contact}" %></h1>

<%= render 'form' %>

<%= link_to 'Back', @phone_number.contact %>